# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - '**' # every branch
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: maven:3.8.5-jdk-11
    steps:
    - name: version
      run: mvn --version
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: lfs
      run: |
        apt update && apt install -y git-lfs
        git lfs install && git lfs pull --include "*.png"

    - name: project check
      run: |
        mvn validate
        mvn compile
        mvn fmt:format

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: doc
      run: mvn javadoc:javadoc

    - name: unittest report
      run: mvn test
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        files: .target/site/jacoco/jacoco.xml
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
